name: Build and Push CyVerse BLAST Backend

on:
  push:
    branches: [main]
    paths:
      - "cyverse-backend/**"
  pull_request:
    branches: [main]
    paths:
      - "cyverse-backend/**"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-digest: ${{ steps.set-digest.outputs.digest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ./cyverse-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pepper-blast-node:latest
          platforms: linux/amd64,linux/arm64
          outputs: type=digest

      - name: Set output digest
        id: set-digest
        run: echo "digest=${{ steps.build-image.outputs.digest }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy using pushed image
        run: |
          DIGEST="${{ needs.build-and-push.outputs.image-digest }}"
          echo "Deploying app with Docker image: $DIGEST"
          # Example: pull and run the exact image
          # docker pull $DIGEST
          # docker run -d -p 8080:8080 $DIGEST
